### ISSUE TITLE
You do not have access to library TestApp, used by your script, or it has been deleted

### ISSUE THREAD

**Issue by oshliaer** [Spencer-Easton/Apps-Script-TestApp-Library#2]
Hello!

Today I can't include library TestApp with the key `Mm17sZ23ccjNtfj2PvKV798h00DPSBbB3`.

It says:

> "You do not have access to library TestApp, used by your script, or it has been deleted"

**Comment by Spencer-Easton** [comment]
Thanks I had moved the script in drive and it had changed permissions. Its fixed now.

**Comment by lavanyaG4** [comment]
Hi, I am also facing the same issuse (You do not have access to library 16lW4CoW8iThJgWQrBwQnqn42HR-P0MomHT7M, used by your script, or it has been deleted.). Can anyone help me. Please let me know what wrong I am doing.
